In [2]:
import pickle as pkl
import matplotlib.pyplot as plt
import numpy as np

In [2]:
with open('D:/Image_Classifier/accuracy.pickle','rb') as f:
    acc = pkl.load(f)

In [16]:
x = np.linspace(0,680,680)
y_val = [acc[i][1] for i in range(680)]
y_acc = [acc[i][0] for i in range(680)]

In [1]:
plt.figure(1,figsize = (8,6),dpi = 800)
plt.plot(x,y_val,label = 'Train Accuracy')
plt.plot(x,y_acc,label = 'Test Accuracy')
plt.text(400,0.6,'Max_train: '+str(y_val[-1]))
plt.text(400,0.65,'Max_test: '+str(y_acc[-1]))
plt.grid()
plt.legend()


NameError: name 'plt' is not defined

In [3]:
import tensorflow as tf
from sklearn.metrics import confusion_matrix
import pickle as pkl

with open('D:/Image_Classifier/batches/test_batch/test_batch.pickle','rb') as f:
    test = pkl.load(f)

In [6]:
import numpy as np

In [12]:

# Load the saved model
model = tf.keras.models.load_model('D:/Image_Classifier/trained_model')

# Load test data
X_test = test[0]
y_true = test[1]

# Make predictions on the test data
y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

# convert one-hot encoded true labels to class labels
y_true = np.argmax(y_true, axis=1)


class_labels = [0, 1, 2]
missing_labels = set(class_labels) - set(np.unique(y_true))
if missing_labels:
    raise ValueError(f"The following labels are missing from y_true: {missing_labels}")

# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_true, y_pred,labels = class_labels)

# Print the confusion matrix
print("Confusion matrix:")
print(conf_matrix)

Confusion matrix:
[[465  60  72]
 [ 54 531  15]
 [ 15   9 576]]
